insert into facts (id, text, added, when) (1, 'St4r and Smurfton were in a boy band once. They had one hit called "Touching Tubes".',  now())
insert into facts (id, text, added, when) (2, 'St4r will do a Firebrand cosplay stream at 1k followers.',  now())
insert into facts (id, text, added, when) (3, 'To this day, St4r can not make it through Rudy without crying.',  now())
insert into facts (id, text, added, when) (4, 'St4r suffers from anatidaephobia. Google it.',  now())
insert into facts (id, text, added, when) (5, 'St4r is unnaturally hairy due to a friend putting Rogaine in his body wash during his formative years.',  now())
insert into facts (id, text, added, when) (6, 'The WR for Sex any% is 00:02 by St4rsurfer. (Any% is where the girl doesn't have to finish.) #condomskipftw',  now())
insert into facts (id, text, added, when) (7, 'St4r whistles on stream to cover up the sound of him farting.',  now())
insert into facts (id, text, added, when) (8, 'The__Sloth is St4r's best friend.', 'st4rsurfer', now())